version: '3.1'

services:
  node:
    build: .
    restart: unless-stopped
    entrypoint:
      - sh
      - docker-entrypoint.sh
    environment:
      - QQID=123123
      - VERIFYKEY=123123
      - ADMINQQID=123123
      - HOST=127.0.0.1
      - PORT=9000
      - SETUAPIKEY=123123123
      - PROXY=http://127.0.0.0:1234
