version: '3.1'

services:
  node:
    build: .
    volumes:
      - ./src:/var/www/qqbot
    restart: unless-stopped
    working_dir: /var/www/qqbot
    entrypoint:
      - sh
      - docker-entrypoint.sh
    environment:
      - QQID=123123
      - VERIFYKEY=123123
      - ADMINQQID=123123
      - HOST=127.0.0.1
      - PORT=9000
