basic:
  qqid: 123123123
  authKey: 123123123
  adminqqid: 123123123
  host: 127.0.0.1
  port: 9000

# 这里定义的是命令的格式，2是一个参数，1是不带参数，permission指定权限，0-4，4是管理员
func:
  nslookup:
    query: 2
    base: 0

  calendar:
    query: 1
    base: 0

  pa:
    query: 1
    base: 0

  ip:
    query: 2
    base: 0
    strict: 1

  help:
    query: 1
    base: 0

  flag:
    query: 2
    base: 0

  rand:
    query: 2
    base: 0

  ban:
    query: 4
    base: 4

  time:
    query: 1
    base: 0

  unban:
    query: 4
    base: 4

  sucker:
    query: 1
    base: 0

  chouxiang:
    query: strings
    base: 0
  
  hello:
    query: 1
    base: 0

  setu:
    query: 1
    base: 0
    strict: 1

  strict:
    query: 5
    base: 4

  alert:
    query: 3
    base: 0

  acg:
    query: 1
    base: 0


user:
  root:
    base: 5

  adminqq:
    base: 5

  "123123":
    base: 4
    allow:
      - "time"
      - "sudo"

group:
  "123456":
    base: 0
    allow:
      - "time"
    ban:
      - "ip"
  "591809200":
    base: 0
    allow:
      - "setu"
    ban:
      - "sudo"
