basic:
  url: "http://127.0.0.1:9000/"
  wsurl: "ws://127.0.0.1:9000/"
  qqid: 123123123
  authKey: 123123123
  adminqqid: 123123123
  host: 127.0.0.1
  port: 9000

# 这里定义的是命令的格式，2是一个参数，1是不带参数，permission指定权限，0-4，4是管理员
func:
  nslookup:
    query: 2
    base: 0

  calendar:
    query: 1
    base: 0

  pa:
    query: 1
    base: 0

  ip:
    query: 2
    base: 0

  help:
    query: 1
    base: 0

  flag:
    query: 2
    base: 0

  time:
    query: 1
    strict: 1
    base: 0

  rand:
    query: 2
    base: 0

  ban:
    query: 4
    base: 4

  unban:
    query: 4
    base: 4

  sucker:
    query: 1
    base: 0

user:
  root:
    base: 5

  "123123":
    base: 4
    allow:
      - "time"
      - "sudo"

group:
  "123456":
    base: 0
    allow:
      - "time"
    ban:
      - "ip"
